import { StyleSheet } from 'react-native';

export const MainScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#E7C0C0',
  },
  backgoroundImageConteiner: {
    flex: 1,
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: -1,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
  },
  characterImageContainer: {
    zIndex: 0,
    width: '100%',
    height: '100%',
    top: '25%',
  },
  rectangle: {
    position: 'absolute',
    top: -100,
    left: '10%',
    width: '80%',
    height: 100,
    borderRadius: 30,
    backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
  },
  hukidashiInnerText: {
    fontSize: 20,
    color: 'white',
  },
  triangle: {
    position: 'absolute',
    top: 0,
    left: '60%',
    transform: [{ scaleX: 2.2 }],
    width: 0,
    height: 0,
    borderTopWidth: 30,
    borderRightWidth: 10,
    borderRightColor: 'transparent',
    borderLeftWidth: 0,
    borderLeftColor: 'transparent',
  },
  characterImage: {
    width: '100%',
    height: '75%',
  },
  backgroundImage: {
    width: '100%',
    height: '100%',
  },
  TopLevelContainer: {
    zIndex: 1,
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  HeaderBtnGroup: {
    flexDirection: 'row',
    position: 'absolute',
    justifyContent: 'flex-end',
    right: 0,
    width: '100%',
  },
  HeaderBtn: {
    width: 40,
    height: 40,
    borderRadius: 40 / 2,
    backgroundColor: 'white',
    borderColor: 'gray',
    borderWidth: 1,
    marginRight: 10,
    marginTop: '5%',
    paddingVertical: 10,
    fontSize: 14,
    textAlign: 'center',
  },
  settingBtnText: {
    textAlign: 'center',
  },
  BottomBtnGroup: {
    top: '80%',
    width: '100%',
    height: '20%',
  },
  BottomBtn: {
    left: '30%',
    width: '80%',
    height: '30%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  leftBtn: {
    flex: 1,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    borderColor: 'white',
    backgroundColor: 'white',
  },
  centerBtn: {
    flex: 1,
    borderColor: 'gray',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    backgroundColor: 'white',
  },
  rightBtn: {
    flex: 1,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    borderColor: 'white',
    backgroundColor: 'white',
  },
  btnText: {
    alignItems: 'center',
    paddingVertical: 30,
  },
});
